apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app  }}
  labels:
    app: {{ .Values.app  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app  }}
  template:
    metadata:
      labels:
        app: {{ .Values.app  }}
    spec:
      containers:
      - name: {{ .Values.app  }}
        image: {{ .Values.image  }}
        resources: 
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}         
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: {{ .Values.application_port  }}
        readinessProbe:
          httpGet:
            scheme: {{ .Values.readinessProbe.httpGet.scheme }} 
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.readinessProbe.httpGet.port }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        livenessProbe:
          httpGet:
            scheme: {{ .Values.livenessProbe.httpGet.scheme }}
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.livenessProbe.httpGet.port }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        startupProbe:
          httpGet:  
            scheme: {{ .Values.startupProbe.httpGet.scheme }}
            path: {{ .Values.startupProbe.httpGet.path }}
            port: {{ .Values.startupProbe.httpGet.port }}
          periodSeconds: {{ .Values.startupProbe.periodSeconds }}
          failureThreshold: {{ .Values.startupProbe.failureThreshold }}
